export const HOTMEMES_LOADING = 'HOTMEMES_LOADING';
export const ADD_HOTMEMES = 'ADD_HOTMEMES';
export const HOTMEMES_FAILED = 'HOTMEMES_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_UPVOTE = 'ADD_UPVOTE';