export const MEMES_LOADING = 'MEMES_LOADING';
export const ADD_MEMES = 'ADD_MEMES';
export const MEMES_FAILED = 'MEMES_FAILED';

export const ADD_COMMENTS = 'ADD_COMMENTS';
export const ADD_COMMENT = 'ADD_COMMENT';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

export const ADD_UPVOTE = 'ADD_UPVOTE';
export const DELETE_UPVOTE = 'DELETE_UPVOTE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';